/**
 * domain/Port.java
 *
 * File generated from the Port uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package domain;

/**
 * Description of the class Port.
 *
 */

public class Port {
		private String city;
		private String country;
		
		public Port(String city, String country) {
			this.city = city;
			this.country = country;
		}
		public String getCity() {   return city;}
		public void setCity(String city) {   this.city = city;	}
		public String getCountry() {   return country;}
		public void setCountry(String country) {   this.country = country; }
}