/**
 * repositories/ShipRepository.java
 *
 * File generated from the ShipRepository uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package domain;

import java.util.List;
import java.util.UUID;

import events.Event;

import infrastructure.AggregateNotFoundException;
import infrastructure.ConcurrencyException;


public class ShipRepository implements IDomainRepository<Ship>{
	private IEventStore eventStore;
	
	public ShipRepository(IEventStore eventStore) {
		this.eventStore = eventStore;
	}

	@Override
	public void save(Ship aggregate) throws ConcurrencyException {
		eventStore.addEvents(aggregate.getId(), aggregate.getUncommitedChanges());
	}

	@Override
	public Ship getById(UUID aggregateId) throws AggregateNotFoundException {
		Ship ship = new Ship(aggregateId);
		List<Event> events = eventStore.getEventsForAggregate(aggregateId);
		ship.loadsFromHistory(events); //Here we fetch all events reflecting the last state for the current aggregate. 
		
		return ship;
	}
}