/**
 * domain/Ship.java
 *
 * File generated from the Ship uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package domain;

import infrastructure.NonExistingShip;
import infrastructure.PrivateAccessor;
import events.ShipArrivalNotifiedEvent;
import events.ShipDepartureNotifiedEvent;
import events.ShipNameChangedEvent;

import java.util.Date;
import java.util.UUID;

public class Ship extends AggregateRoot{
		private String name;
		private Cargo cargo;
		private Port port;
		
		public Ship(){
			super(UUID.randomUUID());
		}
		
		public Ship(UUID shipId){
			super(shipId);
		}
		
		public Ship(String name, Cargo cargo, Port port) {
			this();
			this.name = name;
			this.cargo = cargo;
			this.port = port;
		}
		
		public UUID getId() {return id;	}
		public String getName() {return name;}
		public void setName(String name) {this.name = name;}
		public Cargo getCargo() {return cargo;}
		public void setCargo(Cargo cargo) {this.cargo = cargo;}
		public Port getPort() {return port;}
		public void setPort(Port port) {this.port = port;}
		
		public void setArrival(String fromCity, String fromCountry){
			this.port.setCity(fromCity);
			this.port.setCountry(fromCountry);
		}
		
		public void setDeparture(String toCity, String toCountry){
			this.port.setCity(toCity);
			this.port.setCountry(toCountry);
		}
		
		public void registerEvents() throws NoSuchMethodException, SecurityException{
			registerEvent(ShipNameChangedEvent.class, PrivateAccessor.getPrivateMethod(this,"onShipNameChanged"));
			registerEvent(ShipArrivalNotifiedEvent.class, PrivateAccessor.getPrivateMethod(this,"onShipArrivalNotified"));
			registerEvent(ShipDepartureNotifiedEvent.class, PrivateAccessor.getPrivateMethod(this,"onShipDepartureNotified"));
		}
		
		private void isShipCreated(){
			if(this.id == null){
				try {
					throw new NonExistingShip("The Ship has not been created and no operations can be executed on it.");
				}catch (NonExistingShip e) {
					e.printStackTrace();
				}
			}
		}
		
		//Events Creations
		public void changeName(String newName){
			isShipCreated();
			apply(new ShipNameChangedEvent(this.id, newName));
		}
		public void updateShipArrival(Date occured, Port fromPort){
			isShipCreated();
			apply(new ShipArrivalNotifiedEvent(this.id, this.name, occured, this.cargo, fromPort));
		}
		public void updateShipDeparture(Date occured, Port toPort){
			isShipCreated();
			apply(new ShipDepartureNotifiedEvent(this.id, this.name, occured, this.cargo, toPort));
		}
		
		
		//Events Executions
		@SuppressWarnings("unused")
		private void onShipNameChanged(ShipNameChangedEvent event){
			this.name = event.newName;
		}
		@SuppressWarnings("unused")
		private void onShipArrivalNotified(ShipArrivalNotifiedEvent event){
			this.port = event._FromPort;
		}
		@SuppressWarnings("unused")
		private void onShipDepartureNotified(ShipDepartureNotifiedEvent event){
			this.port = event._ToPort;
		}
}



















