/**
 * command/ShipArrivalCommand.java
 *
 * File generated from the ShipArrivalCommand uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package commands;

import java.util.Date;
import java.util.UUID;

import domain.Port;

/**
 * Description of the class ShipArrivalCommand.
 *
 */

@SuppressWarnings("serial")
public class NotifyShipArrivalCommand implements ICommand {
	private UUID id;
	private Date occured;
	private Port fromPort;

	public NotifyShipArrivalCommand(UUID id, Date occured, String fromPortCity, String fromPortCountry) {
		this.id = id;
		this.occured = occured;
		this.fromPort = new Port(fromPortCity, fromPortCountry);
	}
		
	public UUID getId() {	return id;}
	public Date getOccured() {	return occured;}
	public Port getFromPort() { return fromPort;}
		
}