/**
 * events/DepartureShippedEvent.java
 *
 * File generated from the DepartureShippedEvent uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:35 (4 août 2011) $
 */
package events;

import java.util.Date;
import java.util.UUID;

import domain.Cargo;
import domain.Port;

@SuppressWarnings("serial")
public class ShipDepartureNotifiedEvent extends Event {
	public final Date _Occured;
	public final String _ShipName;
	public final Cargo _Cargo;
	public final Date _Recorded;
	public final Port _ToPort;
		
	public ShipDepartureNotifiedEvent(UUID shipId, String shipName, Date occured, Cargo cargo, Port toPort) {
		super(shipId);
		this._ShipName = shipName;
		this._Cargo = cargo;
		this._Recorded = new Date();
		this._Occured = occured;
		this._ToPort = toPort;
	}
}