/**
 * events/ArrivalShippedEvent.java
 *
 * File generated from the ArrivalShippedEvent uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:35 (4 août 2011) $
 */
package events;

import java.util.Date;
import java.util.UUID;

import domain.Cargo;
import domain.Port;

@SuppressWarnings("serial")
public class ShipArrivalNotifiedEvent extends Event {
		public final Port _FromPort;
		public final String _ShipName;
		public final Cargo _Cargo;
		public final Date _Occured;
		public final Date _Recorded;
 
		public ShipArrivalNotifiedEvent(UUID shipId, String shipName, Date occured, Cargo cargo, Port fromPort) {
			super(shipId);
			this._ShipName = shipName;
			this._Cargo = cargo;
			this._Recorded = new Date();
			this._Occured = occured;
			this._FromPort = fromPort;
		}
}