/**
 * domain/Ship.java
 *
 * File generated from the Ship uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 04/08/11 20:26:34 (4 août 2011) $
 */
package com.linkcorp.dddcqrs.domain;

import java.util.Date;
import java.util.UUID;

import com.linkcorp.dddcqrs.annotations.AggregateRootAnnotation;
import com.linkcorp.dddcqrs.events.ShipArrivalNotifiedEvent;
import com.linkcorp.dddcqrs.events.ShipDepartureNotifiedEvent;
import com.linkcorp.dddcqrs.events.ShipNameChangedEvent;
import com.linkcorp.dddcqrs.infrastructure.NonExistingShip;

@AggregateRootAnnotation
public class Ship extends AggregateRoot{
		private String name;
		private Cargo cargo;
		private Port port;
		
		public Ship(){
			super(UUID.randomUUID());
		}
		
		public Ship(UUID shipId){
			super(shipId);
		}
		
		public Ship(String name, Cargo cargo, Port port) {
			this();
			this.name = name;
			this.cargo = cargo;
			this.port = port;
		}
		
		public UUID getId() {return id;	}
		public String getName() {return name;}
		public void setName(String name) {this.name = name;}
		public Cargo getCargo() {return cargo;}
		public void setCargo(Cargo cargo) {this.cargo = cargo;}
		public Port getPort() {return port;}
		public void setPort(Port port) {this.port = port;}
		
		public void setArrival(String fromCity, String fromCountry){
			this.port.setCity(fromCity);
			this.port.setCountry(fromCountry);
		}
		
		public void setDeparture(String toCity, String toCountry){
			this.port.setCity(toCity);
			this.port.setCountry(toCountry);
		}
		
		private void isShipCreated(){
			if(this.id == null){
				try {
					throw new NonExistingShip("The Ship has not been created and no operations can be executed on it.");
				}catch (NonExistingShip e) {
					e.printStackTrace();
				}
			}
		}
		
		//Events Creations
		public void changeName(String newName){
			isShipCreated();
			ShipNameChangedEvent event = new ShipNameChangedEvent(this.id, newName);
			onShipNameChanged(event);
			apply(event);
		}
		
		public void updateShipArrival(Date occured, Port fromPort){
			isShipCreated();
			ShipArrivalNotifiedEvent event = new ShipArrivalNotifiedEvent(this.id, this.name, occured, this.cargo, fromPort);
			onShipArrivalNotified(event);
			apply(event);
		}
		
		public void updateShipDeparture(Date occured, Port toPort){
			isShipCreated();
			ShipDepartureNotifiedEvent event = new ShipDepartureNotifiedEvent(this.id, this.name, occured, this.cargo, toPort);
			onShipDepartureNotified(event);
			apply(event);
		}
		
		
		//Events Executions
		private void onShipNameChanged(ShipNameChangedEvent event){
			this.name = event.newName;
		}
		
		private void onShipArrivalNotified(ShipArrivalNotifiedEvent event){
			this.port = event._FromPort;
		}
		
		private void onShipDepartureNotified(ShipDepartureNotifiedEvent event){
			this.port = event._ToPort;
		}
}



















